<?xml version="1.0" encoding="utf-8"?><Database Name="mega-book" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=mega-book.database.windows.net;Initial Catalog=mega-book;User ID=kyk0704;Connect Timeout=60" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="mega_bookConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Book" Member="Books">
    <Type Name="Book">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="releaseDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="content" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="isbn" Type="System.String" DbType="Char(13) NOT NULL" CanBeNull="false" />
      <Association Name="Book_review" Member="reviews" ThisKey="Id" OtherKey="bookId" Type="review" />
    </Type>
  </Table>
  <Table Name="dbo.review" Member="reviews">
    <Type Name="review">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="reviewerName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="reviewerDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="content" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="rating" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="bookId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Book_review" Member="Book" ThisKey="bookId" OtherKey="Id" Type="Book" IsForeignKey="true" />
    </Type>
  </Table>
</Database>